// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6_yYBWWjCnitP1qq4rbeQqdBZFDps7nE',
    appId: '1:72340710244:web:acbe2d1e55549b4567d071',
    messagingSenderId: '72340710244',
    projectId: 'vinohradnik-9d9e8',
    authDomain: 'vinohradnik-9d9e8.firebaseapp.com',
    storageBucket: 'vinohradnik-9d9e8.appspot.com',
    measurementId: 'G-M8RRJ4R8M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArLoEGCL7KQSMMf61RGo8A-O_P2vSuHoY',
    appId: '1:72340710244:android:e0872863757f16ed67d071',
    messagingSenderId: '72340710244',
    projectId: 'vinohradnik-9d9e8',
    storageBucket: 'vinohradnik-9d9e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBSU6xps-gqb-cwUoMg9zCaXF8iWw5bNM',
    appId: '1:72340710244:ios:dc8ef19dde95244567d071',
    messagingSenderId: '72340710244',
    projectId: 'vinohradnik-9d9e8',
    storageBucket: 'vinohradnik-9d9e8.appspot.com',
    iosClientId: '72340710244-medq91m6evkmipgdi77vf0i86dbs6dtu.apps.googleusercontent.com',
    iosBundleId: 'com.example.vinohradnik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBSU6xps-gqb-cwUoMg9zCaXF8iWw5bNM',
    appId: '1:72340710244:ios:dc8ef19dde95244567d071',
    messagingSenderId: '72340710244',
    projectId: 'vinohradnik-9d9e8',
    storageBucket: 'vinohradnik-9d9e8.appspot.com',
    iosClientId: '72340710244-medq91m6evkmipgdi77vf0i86dbs6dtu.apps.googleusercontent.com',
    iosBundleId: 'com.example.vinohradnik',
  );
}
